environment_parameters:
  lesson_stage:
    curriculum:
      - name: Stage1_StationaryFixed
        completion_criteria:
          measure: reward
          behavior: Intercept
          signal_smoothing: true
          min_lesson_length: 200000
          # Threshold 22 means it is hitting consistently (Base 20 + Proximity/Time bonuses)
          threshold: 22.0 
        value: 0.0

      - name: Stage2_StationaryRandom
        completion_criteria:
          measure: reward
          behavior: Intercept
          signal_smoothing: true
          min_lesson_length: 200000
          threshold: 23.0
        value: 1.0

      - name: Stage3_MovingCircle
        completion_criteria:
          measure: reward
          behavior: Intercept
          signal_smoothing: true
          min_lesson_length: 300000 # Longer time to adapt to movement
          threshold: 24.0
        value: 2.0

      - name: Stage4_MovingRandom
        completion_criteria:
          measure: reward
          behavior: Intercept
          signal_smoothing: true
          min_lesson_length: 300000
          threshold: 25.0
        value: 3.0

      - name: Stage5_HighSpeed
        # Final stage, no completion criteria
        value: 4.0

behaviors:
  Intercept:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 64
    summary_freq: 50000
    threaded: True